frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.persistenceMaxQPS:
- value: 3000
  constraints: {}
frontend.persistenceMaxQPS:
- value: 3000
  constraints: {}
frontend.historyMgrNumConns:
- value: 10
  constraints: {}
frontend.throttledLogRPS:
- value: 20
  constraints: {}
history.historyMgrNumConns:
- value: 50
  constraints: {}
system.advancedVisibilityWritingMode:
- value: "off"
  constraints: {}
matching.getTaskBatchSize:
- value: 30
  constraints: {}
matching.numTaskqueueReadPartitions:
- value: 10
  constraints: {}
matching.numTaskqueueWritePartitions:
- value: 10
  constraints: {}
